# указываем версию docker-compose которую будем сейчас использовать
version: '3.9'

# создаем поле для наших сервисов (контейнеров)
services:

  # создаем сервис и даем ему название
  postgres-db:
    # берем образ postgres из docker hub для нашего текущего сервиса
    image: postgres:latest
    # даем название для текущего контенера(сервиса), с помощью которого будем связывать с другими контейнерами(сервисами)
    container_name: postgres
    # переменные окружения для текущего сервиса 
    # переменные берутся из описания основного образа для нашего сервиса
    environment:
      # ник пользователя подключеного к базе 
      POSTGRES_USER: postgres
      # пароль для входа в базу для текущего пользтователя
      POSTGRES_PASSWORD: 1856
      # название для нашой уже существующей базы данных
      POSTGRES_DB: my_name_db
    # порт от локальной машины пользователя(меня) к текущему контейнеру : порт от текущего контейнера к локальной машине пользолвателя(меня)
    ports:
      - "5432:5432"